[package]
name = "pinar-derive"
version = "0.1.0"
authors = ["Sebastien Chapuis <sebastien@chapu.is>"]
edition = "2018"
description = "macro derives for pinar"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.22"
quote = "0.6.10"
